# Generated by Django 4.0.5 on 2022-06-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyevent',
            name='feature_image',
            field=models.FileField(upload_to='images/%Y/%m/%d'),
        ),
    ]
