# Generated by Django 4.0.5 on 2022-06-28 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_rename_feature_image_companyevent_feature_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyevent',
            name='feature_images',
        ),
        migrations.CreateModel(
            name='CompanyEventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_images', models.ImageField(upload_to='')),
                ('companyEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.companyevent')),
            ],
        ),
    ]
