# Generated by Django 4.0.5 on 2022-06-29 07:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_companyeventphoto_companyevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('partner_logo', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
