# Generated by Django 4.0.5 on 2022-06-24 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_tag_category_rename_tags_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='body',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='product',
        ),
        migrations.AddField(
            model_name='brand',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='products.brand'),
            preserve_default=False,
        ),
    ]
